# Generated by Django 5.0 on 2023-12-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_class_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='expire',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
