# Generated by Django 5.0 on 2024-01-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userprofile_section_alter_userprofile_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
