# Generated by Django 5.0 on 2024-01-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_class_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
