# Generated by Django 5.0 on 2024-01-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_temp_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='expire',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
