# Generated by Django 5.0 on 2024-01-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_hod_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod_attendance',
            name='roll_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
